### ISSUE TITLE
commit 96416d5d0bb6f8c2356fa067f707f34fc650688c causes 105-ntpauth test to fail on all architectures

### ISSUE THREAD

**Issue by markkp** [mlichvar/clknetsim#1]
Prior to this commit, all tests executed by "make check" worked.  After this, I see the following on x86_64:
 105-ntpauth (14/31)
 Testing NTP authentication:
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_conf=keyfile tmp/keys
       client_server_options=key 1
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking source selection:
       node 2:                                              OK
     checking mean/min incoming/outgoing packet interval:
       node 1: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
       node 2: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
     checking clock sync time, max/rms time/freq error:
       node 2: 132 1.37e-04 1.32e-06 6.89e-05 1.18e-07      OK
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_conf=keyfile tmp/keys
       client_server_options=key 2
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking source selection:
       node 2:                                              OK
     checking mean/min incoming/outgoing packet interval:
       node 1: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
       node 2: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
     checking clock sync time, max/rms time/freq error:
       node 2: 132 1.37e-04 1.32e-06 6.89e-05 1.18e-07      OK
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_conf=keyfile tmp/keys
       client_server_options=key 3
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking source selection:
       node 2:                                              OK
     checking mean/min incoming/outgoing packet interval:
       node 1: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
       node 2: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
     checking clock sync time, max/rms time/freq error:
       node 2: 132 1.37e-04 1.32e-06 6.89e-05 1.18e-07      OK
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_conf=keyfile tmp/keys
       client_server_options=key 4
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking source selection:
       node 2:                                              OK
     checking mean/min incoming/outgoing packet interval:
       node 1: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
       node 2: 3.34e+02 3.34e+02 6.42e+01 6.42e+01          OK
     checking clock sync time, max/rms time/freq error:
       node 2: 132 1.37e-04 1.32e-06 6.89e-05 1.18e-07      OK
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_conf=keyfile tmp/keys
       client_server_options=key 4
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking clock sync time, max/rms time/freq error:
       node 2: 10001 1.10e+00 1.00e-04 6.73e-01 1.00e-04    BAD
     checking mean/min incoming/outgoing packet interval:
       node 1: 4.31e+02 4.31e+02 6.41e+01 6.41e+01          OK
       node 2: 4.31e+02 4.31e+02 6.41e+01 6.41e+01          OK
   network with 1_1 servers and 1 clients:
     non-default settings:
       client_server_options=key 4
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
     checking clock sync time, max/rms time/freq error:
       node 2: 10001 1.10e+00 1.00e-04 6.73e-01 1.00e-04    BAD
     checking mean/min incoming/outgoing packet interval:
       node 1: inf inf inf inf                              OK
       node 2: inf inf inf inf                              OK
   network with 1_1 servers and 2 clients:
     non-default settings:
       base_delay=1e-4 (_ -1 (equal 0.1 from 3) (equal 0.1 to 1))
       client_conf=keyfile tmp/keys
       client_lpeer_options=key 1
       client_rpeer_options=key 1
       client_server_options=key 4
       clients=2
       max_sync_time=300
       peers=2
       server_conf=keyfile tmp/keys
     starting node 1:                                       OK
     starting node 2:                                       OK
     starting node 3:                                       OK
     running simulation:                                    OK
     checking chronyd exit:
       node 1:                                              OK
       node 2:                                              OK
       node 3:                                              OK
     checking clock sync time, max/rms time/freq error:
       node 2: 132 1.09e-04 1.63e-06 5.70e-05 1.93e-07      OK
       node 3: 325 1.32e-01 8.33e-02 6.39e-03 1.20e-03      BAD
 FAIL

The results on x86, ppc64le, s390, and s390x are similar.

**Comment by mlichvar** [comment]
This is actually a bug in the chrony test suite, which was introduced in 2.2.1 and which was exposed later by the clknetsim commit. It should be now fixed in chrony git (commit 9749a1c6fcbdbf158bef2e0b454e7044a742749a).
